[workspace]
members = ["crates/varchar", "crates/varchar-cli"]
resolver = "3"

[workspace.package]
edition = "2024"
rust-version = "1.97"
version = "0.1.2"
license = "MIT"
repository = "https://github.com/BalajiLeninrajan/varchar"
homepage = "https://varchar.balajileninrajan.dev"
authors = ["Balaji Leninrajan <bleninrajan@gmail.com>"]

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
